
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ANIO CONSTANTES DIA ESTADO MES NOMBRE PRIMER_APELLIDO RENAPO SEGUNDO_APELLIDO SEXOcurp : PRIMER_APELLIDO SEGUNDO_APELLIDO NOMBRE ANIO MES DIA SEXO ESTADO CONSTANTES RENAPO'
    
_lr_action_items = {'PRIMER_APELLIDO':([0,],[2,]),'$end':([1,11,],[0,-1,]),'SEGUNDO_APELLIDO':([2,],[3,]),'NOMBRE':([3,],[4,]),'ANIO':([4,],[5,]),'MES':([5,],[6,]),'DIA':([6,],[7,]),'SEXO':([7,],[8,]),'ESTADO':([8,],[9,]),'CONSTANTES':([9,],[10,]),'RENAPO':([10,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'curp':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> curp","S'",1,None,None,None),
  ('curp -> PRIMER_APELLIDO SEGUNDO_APELLIDO NOMBRE ANIO MES DIA SEXO ESTADO CONSTANTES RENAPO','curp',10,'p_curp','app.py',65),
]
